spring.application.name=ApiFinanca

spring.datasource.url=jdbc:postgresql://localhost:5432/financas_db
spring.datasource.username=postgres
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

app.jwt.secret=change-this-secret-key-to-a-secure-value
app.jwt.expiration=3600000

# Springdoc OpenAPI configuration
springdoc.override-with-generic-response=false